#!/bin/bash

cd DiffViewer
java -cp lib/antlr.jar:lib/asm-attrs.jar:lib/asm.jar:lib/aws-java-sdk-1.2.11-javadoc.jar:lib/aws-java-sdk-1.2.11-sources.jar:lib/aws-java-sdk-1.2.11.jar:lib/c3p0-0.9.0.jar:lib/cglib-2.1.3.jar:lib/commons-codec-1.4.jar:lib/commons-collections-2.1.1.jar:lib/commons-logging-1.0.4.jar:lib/commons-logging-1.1.1.jar:lib/diffutils-1.2.1.jar:lib/dom4j-1.6.1.jar:lib/ehcache-1.1.jar:lib/hibernate3.jar:lib/httpclient-4.1.2.jar:lib/httpclient-cache-4.1.2.jar:lib/httpcore-4.1.2.jar:lib/httpmime-4.1.2.jar:lib/javaparser-1.0.8.jar:lib/jta.jar:lib/junit-4.4.jar:lib/log4j-1.2.9.jar:lib/sqlite-jdbc-3.7.2.jar:lib/sqlitejdbc-v056.jar:lib/witch_doctor_data_models.jar:lib/xml-apis.jar:bin:. DiffViewer
cd ..
